name: Checks

on:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npx tsc

  tests:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npx jest

  linting:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npx eslint

  CVEs:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/checkout@v2
    - run: |
        npm ci
        tsc
        bin/cli validate --schema BCVE CVEs

  formatting:
    needs: linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/checkout@v2
    - run: |
        npm i prettier # no need to install the entire project here
        npx prettier -c .
