name: Checks

on:
  pull_request:
  push:

jobs:
  check-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npx tsc

  check-tests:
    needs: check-compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npx jest

  check-linting:
    needs: check-compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npx eslint

  check-CVEs:
    needs: check-compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v2
    - run: |
        npm ci
        tsc
        bin/cli check --schema BCVE CVEs/*.json

  check-formatting:
    needs: check-linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v2
    - run: |
        npm i prettier # no need to install the entire project here
        npx prettier -c .
