# Sanity checks the various data formats
name: Data formats
on: [push]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          npm ci
          npm run-script build

      - name: check CVEs
        run: |
          bin/cli check --schema BCVE CVEs/*.json

      - name: check Export
        run: |
          bin/cli export '*'
          bin/cli check --schema Export work/export/*.json
