# Sanity checks the various install scripts. This is kept up to date manually.
name: Install scripts
on:
  workflow_dispatch:
  schedule:
    - cron: '22 20 * * 1'

jobs:
  install-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-latest]
    steps:
      - uses: actions/setup-node@v1
      - name: checkout
        uses: actions/checkout@v2
      - name: install (non-windows)
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        run: |
          ./contrib/tools/eslint/installers/install.sh $TMP/eslint-dir
          ./contrib/tools/codeql/installers/install.sh $TMP/codeql-dir
#          ./contrib/tools/nodejsscan/installers/install.sh $TMP/nodejsscan-dir
        env:
          TMP: ${{ runner.temp }}

      - name: install (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell
        run: |
          ./contrib/tools/eslint/bin/install.cmd $env:TMP/eslint-dir
        env:
          TMP: ${{ runner.temp }}
