# Sanity checks the various install scripts. This is kept up to date manually.
name: Install scripts
on: [workflow_dispatch]
jobs:
  install-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: checkout
        uses: actions/checkout@v2
      - name: install (non-windows)
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        run: |
          ./contrib/tools/eslint/bin/install.sh $TMP/eslint-dir
          ./contrib/tools/codeql/bin/install.sh $TMP/codeql-dir
          ./contrib/tools/nodejsscan/bin/install.sh $TMP/nodejsscan-dir
          ./contrib/tools/pmd/bin/install.sh $TMP/pmd-dir
        env:
          TMP: ${{ runner.temp }}

      - name: install (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell
        run: |
          ./contrib/tools/eslint/bin/install.cmd $env:TMP/eslint-dir
          ./contrib/tools/codeql/bin/install.cmd $env:TMP/codeql-dir
        env:
          TMP: ${{ runner.temp }}
